In [3]:
import numpy as np

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [10]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [11]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [12]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Eşit aralıklı dizi oluşturma . Arange ile farkı stop 

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random numpy
harici çıkış


In [14]:
np.random.randn(4)

array([ 0.93888557,  0.85353909, -1.34412416,  0.88159197])

In [17]:
np.random.randint(1,10)

7

In [25]:
np.random.randint(1,10,5)

array([9, 5, 9, 2, 1])

## Numpy dizi methotları

In [29]:
benimNumpyDizim=np.random.randint(1,100,30)

In [30]:
benimNumpyDizim

array([84, 14, 40, 25, 78, 17, 27, 91, 70, 69, 32, 82, 13, 94, 93, 42,  9,
        9, 87, 28, 31, 21, 86, 51, 94, 87, 55, 85, 42, 85])

In [32]:
benimNumpyDizim.reshape(5,6)

array([[84, 14, 40, 25, 78, 17],
       [27, 91, 70, 69, 32, 82],
       [13, 94, 93, 42,  9,  9],
       [87, 28, 31, 21, 86, 51],
       [94, 87, 55, 85, 42, 85]])

In [33]:
benimNumpyDizim.reshape(6,5)

array([[84, 14, 40, 25, 78],
       [17, 27, 91, 70, 69],
       [32, 82, 13, 94, 93],
       [42,  9,  9, 87, 28],
       [31, 21, 86, 51, 94],
       [87, 55, 85, 42, 85]])

In [34]:
benimNumpyDizim.max()

94

In [35]:
benimNumpyDizim.argmax()

13

## slicing 

In [38]:
benimDizim=np.arange(0,15)

In [39]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
benimDizim[3:8]=-5

In [41]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [42]:
baskaDizi=np.arange(0,24)

In [48]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [49]:
slicingDizi=baskaDizi[4:9]

In [50]:
slicingDizi[:]=100

In [51]:
slicingDizi

array([100, 100, 100, 100, 100])

In [52]:
baskaDizi

array([  0,   1,   2,   3, 100, 100, 100, 100, 100,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [89]:
ornekDizi=np.arange(1,10)

In [90]:
ornekDizi

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
ornekKopyasi=ornekDizi.copy()

In [92]:
ornekKopyasi

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
ornekKopyasiSlicing=ornekKopyasi[0:5]

In [96]:
ornekKopyasiSlicing

array([1, 2, 3, 4, 5])

In [97]:
ornekKopyasiSlicing[:]=0

In [98]:
ornekDizi

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
ornekKopyasi

array([0, 0, 0, 0, 0, 6, 7, 8, 9])

In [100]:
ornekKopyasiSlicing

array([0, 0, 0, 0, 0])

## indexleme


In [101]:
benimListem=[[1,2,3],[4,5,6],[7,8,9]]

In [102]:
benimYeniDizim=np.array(benimListem)

In [103]:
benimYeniDizim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
benimYeniDizim[0,2]

3

In [105]:
benimYeniDizim[0][2]

3

In [106]:
benimYeniDizim[0]

array([1, 2, 3])

In [108]:
benimYeniDizim[2:,2:]

array([[9]])

In [109]:
benimYeniDizim[[0]]

array([[1, 2, 3]])

In [110]:
benimYeniDizim[[2,1,0]]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

## numpy operations

In [122]:
newArray=np.random.randint(1,100,20)

In [123]:
newArray

array([80, 35, 49, 48,  9, 13, 12, 23, 32, 23, 20, 93, 93, 40, 55, 80,  3,
       73, 24, 29])

In [129]:
newArray>25

array([ True,  True,  True,  True, False, False, False, False,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
       False,  True])

In [130]:
sonucDizisi=newArray>24

In [131]:
sonucDizisi

array([ True,  True,  True,  True, False, False, False, False,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
       False,  True])

In [132]:
newArray[sonucDizisi]

array([80, 35, 49, 48, 32, 93, 93, 40, 55, 80, 73, 29])

In [133]:
newArray[newArray >25]

array([80, 35, 49, 48, 32, 93, 93, 40, 55, 80, 73, 29])

In [134]:
sonDizi= np.arange(0,24)

In [136]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [135]:
sonDizi+ sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [137]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [138]:
sonDizi / sonDizi

<ipython-input-138-20a5ae775714>:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [139]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])